version: '2'
services:
  mysql:
    image: mysql:8.0.21
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: abmProducts
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      USER: 1000

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  beanstalkd:
    image: schickling/beanstalkd
    hostname: beanstalk
    links:
      - redis
      - mysql
    ports:
      - "11300:11300"

  web:
    image: matiasgb/php-nginx:php7.4
    hostname: dev
    links:
      - mysql
      - redis
      - beanstalkd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/sites-available
      - ./ssl:/etc/nginx/ssl
      - ../:/var/www
    environment:
      TZ: "America/Argentina/Cordoba"
      COMPOSER_CACHE_DIR: /var/www/.composer
      COMPOSER_HOME: /var/www/.composer
      XDEBUG_CONFIG: "remote_host=172.23.0.1"
      PHP_IDE_CONFIG: "serverName=Dobi"
